apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ddk-repository
  description: Eclipse P2 update site repository
  labels:
    frontseat.dev/language: java
  annotations:
    frontseat.dev/plugins: tycho
spec:
  type: library
  lifecycle: production
  owner: dsl-devkit-team
  system: dsl-devkit
  dependsOn:
    - component:default/com.avaloq.tools.ddk.feature
    - component:default/com.avaloq.tools.ddk.runtime.feature
  projects:
    - ddk-repository
