apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com.avaloq.tools.ddk.check.ide
  description: Check DSL IDE/LSP support
  labels:
    frontseat.dev/language: java
  annotations:
    frontseat.dev/plugins: tycho
spec:
  type: library
  lifecycle: production
  owner: dsl-devkit-team
  system: dsl-devkit
  dependsOn:
    - component:default/com.avaloq.tools.ddk.check.core
    - component:default/com.avaloq.tools.ddk.check.runtime.core
  dependencyOf:
    - component:default/com.avaloq.tools.ddk.check.ui
    - component:default/com.avaloq.tools.ddk.feature
  projects:
    - com.avaloq.tools.ddk.check.ide
