apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com.avaloq.tools.ddk.xtext.export.generator
  description: Export DSL code generator
  labels:
    frontseat.dev/language: java
  annotations:
    frontseat.dev/plugins: tycho
spec:
  type: library
  lifecycle: production
  owner: dsl-devkit-team
  system: dsl-devkit
  dependsOn:
    - component:default/com.avaloq.tools.ddk.xtext
    - component:default/com.avaloq.tools.ddk.xtext.export
    - component:default/com.avaloq.tools.ddk.xtext.expression
    - component:default/com.avaloq.tools.ddk.xtext.generator
  dependencyOf:
    - component:default/com.avaloq.tools.ddk.feature
  projects:
    - com.avaloq.tools.ddk.xtext.export.generator
