[plugins]
frontseat = "https://github.com/frontseat-dev/frontseat-mise.git"

[tools]
"frontseat:frontseat" = { version = "latest", plugins = "backstage,github,mise,release-conventional-commits,release-flow,tycho,maven" }

[shell_alias]
fs = "frontseat"

[tasks.dev]
description = "Start Backstage via Docker Compose"
run = "docker compose up"

[settings]
experimental = true
