apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com.avaloq.tools.ddk.xtext.check.generator
  description: Check DSL Xtend-based code generator
  labels:
    frontseat.dev/language: java
  annotations:
    frontseat.dev/plugins: tycho
spec:
  type: library
  lifecycle: production
  owner: dsl-devkit-team
  system: dsl-devkit
  dependsOn:
    - component:default/com.avaloq.tools.ddk.check.runtime.core
  dependencyOf:
    - component:default/com.avaloq.tools.ddk.feature
    - component:default/com.avaloq.tools.ddk.workflow
  projects:
    - com.avaloq.tools.ddk.xtext.check.generator
