apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com.avaloq.tools.ddk.xtext.expression.ui
  description: Expression DSL Eclipse UI
  labels:
    frontseat.dev/language: java
  annotations:
    frontseat.dev/plugins: tycho
spec:
  type: library
  lifecycle: production
  owner: dsl-devkit-team
  system: dsl-devkit
  dependsOn:
    - component:default/com.avaloq.tools.ddk.xtext.expression
    - component:default/com.avaloq.tools.ddk.xtext.expression.ide
  dependencyOf:
    - component:default/com.avaloq.tools.ddk.feature
    - component:default/com.avaloq.tools.ddk.xtext.export.ui
    - component:default/com.avaloq.tools.ddk.xtext.generator
    - component:default/com.avaloq.tools.ddk.xtext.scope.ui
  projects:
    - com.avaloq.tools.ddk.xtext.expression.ui
