apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com.avaloq.tools.ddk
  description: Base DDK runtime plugin
  labels:
    frontseat.dev/language: java
  annotations:
    frontseat.dev/plugins: tycho
spec:
  type: library
  lifecycle: production
  owner: dsl-devkit-team
  system: dsl-devkit
  dependencyOf:
    - component:default/com.avaloq.tools.ddk.check.runtime.core
    - component:default/com.avaloq.tools.ddk.runtime.feature
    - component:default/com.avaloq.tools.ddk.test.core
    - component:default/com.avaloq.tools.ddk.test.ui
    - component:default/com.avaloq.tools.ddk.xtext
    - component:default/com.avaloq.tools.ddk.xtext.builder
    - component:default/com.avaloq.tools.ddk.xtext.test.core
    - component:default/com.avaloq.tools.ddk.xtext.ui
  projects:
    - com.avaloq.tools.ddk
