apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com.avaloq.tools.ddk.check.test.runtime.tests
  description: Tests for Check DSL test runtime
  labels:
    frontseat.dev/language: java
  annotations:
    frontseat.dev/plugins: tycho
spec:
  type: library
  lifecycle: production
  owner: dsl-devkit-team
  system: dsl-devkit
  dependsOn:
    - component:default/com.avaloq.tools.ddk.check.core.test
    - component:default/com.avaloq.tools.ddk.check.runtime.core
    - component:default/com.avaloq.tools.ddk.check.test.runtime
    - component:default/com.avaloq.tools.ddk.check.test.runtime.ui
  dependencyOf:
    - component:default/com.avaloq.tools.ddk.xtext.test
  projects:
    - com.avaloq.tools.ddk.check.test.runtime.tests
