apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com.avaloq.tools.ddk.xtext.valid.ui
  description: Valid DSL Eclipse UI (deprecated)
  labels:
    frontseat.dev/language: java
  annotations:
    frontseat.dev/plugins: tycho
spec:
  type: library
  lifecycle: production
  owner: dsl-devkit-team
  system: dsl-devkit
  dependsOn:
    - component:default/com.avaloq.tools.ddk.xtext.ui
    - component:default/com.avaloq.tools.ddk.xtext.valid
    - component:default/com.avaloq.tools.ddk.xtext.valid.ide
  dependencyOf:
    - component:default/com.avaloq.tools.ddk.feature
  projects:
    - com.avaloq.tools.ddk.xtext.valid.ui
