apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com.avaloq.tools.ddk.xtext.expression.ide
  description: Expression DSL IDE/LSP support
  labels:
    frontseat.dev/language: java
  annotations:
    frontseat.dev/plugins: tycho
spec:
  type: library
  lifecycle: production
  owner: dsl-devkit-team
  system: dsl-devkit
  dependsOn:
    - component:default/com.avaloq.tools.ddk.xtext.expression
  dependencyOf:
    - component:default/com.avaloq.tools.ddk.feature
    - component:default/com.avaloq.tools.ddk.xtext.expression.ui
  projects:
    - com.avaloq.tools.ddk.xtext.expression.ide
