apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com.avaloq.tools.ddk.test.ui
  description: Eclipse UI test support for DSLs
  labels:
    frontseat.dev/language: java
  annotations:
    frontseat.dev/plugins: tycho
spec:
  type: library
  lifecycle: production
  owner: dsl-devkit-team
  system: dsl-devkit
  dependsOn:
    - component:default/com.avaloq.tools.ddk
    - component:default/com.avaloq.tools.ddk.test.core
  dependencyOf:
    - component:default/com.avaloq.tools.ddk.check.runtime.core.test
    - component:default/com.avaloq.tools.ddk.check.ui.test
    - component:default/com.avaloq.tools.ddk.feature
    - component:default/com.avaloq.tools.ddk.test.ui.test
    - component:default/com.avaloq.tools.ddk.xtext.test.core
  projects:
    - com.avaloq.tools.ddk.test.ui
