apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com.avaloq.tools.ddk.xtext.common.types.ui
  description: Xtext common types Eclipse UI
  labels:
    frontseat.dev/language: java
  annotations:
    frontseat.dev/plugins: tycho
spec:
  type: library
  lifecycle: production
  owner: dsl-devkit-team
  system: dsl-devkit
  dependsOn:
    - component:default/com.avaloq.tools.ddk.xtext.common.types
  dependencyOf:
    - component:default/com.avaloq.tools.ddk.check.ui
    - component:default/com.avaloq.tools.ddk.runtime.feature
  projects:
    - com.avaloq.tools.ddk.xtext.common.types.ui
