apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com.avaloq.tools.ddk.xtext.test
  description: Xtext test support utilities
  labels:
    frontseat.dev/language: java
  annotations:
    frontseat.dev/plugins: tycho
spec:
  type: library
  lifecycle: production
  owner: dsl-devkit-team
  system: dsl-devkit
  dependsOn:
    - component:default/com.avaloq.tools.ddk.check.core.test
    - component:default/com.avaloq.tools.ddk.check.runtime.core.test
    - component:default/com.avaloq.tools.ddk.check.test.runtime.tests
    - component:default/com.avaloq.tools.ddk.check.ui.test
    - component:default/com.avaloq.tools.ddk.checkcfg.core.test
    - component:default/com.avaloq.tools.ddk.checkcfg.ui.test
    - component:default/com.avaloq.tools.ddk.sample.helloworld.ui.test
    - component:default/com.avaloq.tools.ddk.test.core
    - component:default/com.avaloq.tools.ddk.typesystem.test
    - component:default/com.avaloq.tools.ddk.xtext
    - component:default/com.avaloq.tools.ddk.xtext.builder
    - component:default/com.avaloq.tools.ddk.xtext.export.test
    - component:default/com.avaloq.tools.ddk.xtext.format.test
    - component:default/com.avaloq.tools.ddk.xtext.generator
    - component:default/com.avaloq.tools.ddk.xtext.generator.test
    - component:default/com.avaloq.tools.ddk.xtext.test.core
    - component:default/com.avaloq.tools.ddk.xtext.ui
    - component:default/com.avaloq.tools.ddk.xtext.ui.test
  dependencyOf:
    - component:default/com.avaloq.tools.ddk.workflow
  projects:
    - com.avaloq.tools.ddk.xtext.test
